In [1]:
import numpy as np
np.__version__

'1.14.2'

In [2]:
import pandas as pd ## Pandas is very fast
pd.__version__

'0.22.0'

## Data frames 

In [95]:
 ## one-dimensional array of indexed data
 ## a specialization of a Python dictionary   
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [9]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [11]:
data.values[0] ## same as data[0]

0.25

In [13]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [20]:
## can be accessed via index nmaenb mi 19*/
data['a']


0.25

Pandas Series makes it much more efficient than Python dictionaries for certain operations. Pandas used type-specific similar to numpy vs list speed up.

In [21]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [22]:
population['California']

38332521

In [25]:
print(population[0])
print(population.index)

38332521
Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')


In [27]:
pd.Series({2:'a', 1:'b', 3:'c'}) ## data can be a dictionary

1    b
2    a
3    c
dtype: object

In [28]:
# series is populated only with the explicitly identified keys.
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [29]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [89]:
list(area.items())

[('California', 423967),
 ('Florida', 170312),
 ('Illinois', 149995),
 ('New York', 141297),
 ('Texas', 695662)]

In [36]:
goat_dict=pd.Series({'NBA':"Kobe Bryant", 'NFL':"Tom Brady",'Variety Show':'Running Man'})

In [37]:
goat_dict

NBA             Kobe Bryant
NFL               Tom Brady
Variety Show    Running Man
dtype: object

In [38]:
## pd dataframes is just a sequence of series
states = pd.DataFrame({'population': population,
                       'area': area})
print(states)

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [41]:
print(states.index)
print(states.columns)

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')
Index(['area', 'population'], dtype='object')


In [40]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [83]:
states.keys() ## colnames in dataframe with at least 2 columns
## In dataframe with 1 column or series, it's the rownames

Index(['area', 'population'], dtype='object')

In [90]:
list(states.items())

[('area', California    423967
  Florida       170312
  Illinois      149995
  New York      141297
  Texas         695662
  Name: area, dtype: int64), ('population', California    38332521
  Florida       19552860
  Illinois      12882135
  New York      19651127
  Texas         26448193
  Name: population, dtype: int64)]

In [43]:
print(states['area'])
print(states['population'])

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
Name: population, dtype: int64


In [49]:
# single column df from a series
pd.DataFrame(population, columns=['population']) 

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

In [51]:
data = [{'a': i, 'b': 2 * i} for i in range(3)] ##
##pd.DataFrame({'a':np.arange(3),'b':np.arange(3) * 2})
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [55]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [107]:
pd.DataFrame([{'a': 1, 'b': 2,'b': 3, 'c': 4}]) ## different than above

a  b  c
0  1  3  4

In [63]:
## Panda index: immutable array or as an ordered set 
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [67]:
#immutable array, cannot change it
ind[1] = 0 

TypeError: Index does not support mutable operations

In [65]:
## Indexing works like numpy array
print(ind[1])
print(ind[::2])
print(ind.size)



3
Int64Index([2, 5, 11], dtype='int64')
5


In [68]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [69]:
# intersection
indA & indB ## same as indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [70]:
# Union
indA | indB ## same as indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [71]:
# complement of (A & B) 
indA ^ indB ## indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

## Indexing

In [112]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [98]:
'a' in data

True

In [99]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [100]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [101]:
## Series objects can even be modified with a dictionary-like syntax
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [104]:
data['a':'c'] ## same as data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [105]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [106]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Explicit(`loc`) and implicit (`iloc`) indexing

In [115]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [118]:
# explicit index when indexing
data[3] ## 1,3,5 works, see counter example below

'b'

In [ ]:
## Recall that 
data2 = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data2[0]

In [133]:
# implicit index when slicing
print(data[1]) ## data.loc[1]
print('\n')
print(data[1:3]) ## this works similarily as above
## These are confusing therefore use loc and iloc for these

a


3    b
5    c
dtype: object


In [135]:
## explicit
data.loc[1:5]

1    a
3    b
5    c
dtype: object

In [136]:
data.loc[3]

'b'

In [132]:
## implicit
data.iloc[1]

'b'

In [138]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [139]:
data['area'] is data.area ## same thing bro as long as `area` is not a function

True

In [140]:
data['pop'] is data.pop ## therefore data['pop'] is recommended

False

In [141]:
data.pop ## is acutally a function

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193>

In [146]:
data['density'] = data['pop'] / data['area']
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01]])

In [147]:
data.T

California       Florida      Illinois      New York         Texas
area     4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05  6.956620e+05
pop      3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07  2.644819e+07
density  9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02  3.801874e+01

In [156]:
data.values[0] ## work like numpy array

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [161]:
data.iloc[3:5,0:2] ## implicit

area       pop
New York  141297  19651127
Texas     695662  26448193

In [160]:
data.loc['Florida':,:'pop'] ## explicit

area       pop
Florida   170312  19552860
Illinois  149995  12882135
New York  141297  19651127
Texas     695662  26448193

The `ix` indexer allows a hybrid of these two approaches, however, it is subject to the same potential sources of confusion if series is indeded by integers

In [162]:
data

area       pop     density
California  423967  38332521   90.413926
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [167]:
data.ix[:3,:'pop']

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135

In [168]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [169]:
data.ix[data.density > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [170]:
data.loc[data['density'] > 100, ['pop', 'density']]

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [182]:
data.loc[data.iloc[:,2] > 100, ['pop', 'density'] ] ##data.iloc won't work here

pop     density
Florida   19552860  114.806121
New York  19651127  139.076746

In [188]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

In [189]:
data.loc['California', 'density'] = 89
data

area       pop     density
California  423967  38332521   89.000000
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763
New York    141297  19651127  139.076746
Texas       695662  26448193   38.018740

#### Directly indexing on df referes to slicing (row indexing)

In [193]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [249]:
data[1:3]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [251]:
data[0:1] ## works but not data[0]

area       pop  density
California  423967  38332521     89.0

In [195]:
data[data.density > 100]

area       pop     density
Florida   170312  19552860  114.806121
New York  141297  19651127  139.076746

### Operating on panda data frames

In [205]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [207]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [206]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [208]:
np.exp(df)

A            B           C            D
0   403.428793  8103.083928    7.389056   403.428793
1  1096.633158    54.598150   20.085537  1096.633158
2  1096.633158     7.389056  148.413159    54.598150

In [213]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [214]:
population / area ## union was taken `area.index | population.index`

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [215]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B ## or A.add(B) similar as above, union is takend and index are matched explicitely

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [216]:
## replace NaN with values
A.add(B,fill_value=0) 

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [217]:
list('AB')

['A', 'B']

In [218]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [219]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [220]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [222]:
A.add(B,fill_value=0)

A     B    C
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0

In [232]:
A.add(B,fill_value=np.mean(A.values))
# same as `A.add(B, fill_value=A.stack().mean())`

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [236]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [243]:
df.iloc[0] # same as df.iloc[0,:]

Q    3
R    8
S    2
T    4
Name: 0, dtype: int32

In [253]:
df - df.iloc[0] 

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [269]:
np.squeeze(np.array(df[0:1]))

array([3, 8, 2, 4])

In [270]:
df - np.squeeze(np.array(df[0:1])) ##works

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [257]:
df- df.values[0] ## works as well

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [280]:
df.subtract(df['R'], axis=0) ## same as (df.T-df['R']).T

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [301]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [302]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

### Missing values
Pandas chose to use sentinels for missing data and further chose to use two already-existing Python null values: the special floating-point `NaN` value, and the Python `None` object

In [303]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

Operating on object is slow and alos aggregations like `sum` and `min` with `None` will return error: `vals1.sum()` will not work

In [305]:
vals2 = np.array([1, np.nan, 3, 4]) 
vals2.dtype

dtype('float64')

In [307]:
print(1 + np.nan)
print(0 * np.nan)
vals2.sum() 

nan
nan


nan

In [308]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2) ## ignoring NaN

(8.0, 1.0, 4.0)

`NaN` and `None` both have their place, and Pandas is built to handle the two of them nearly interchangeably, converting between them where appropriate:

In [309]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [310]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int32

In [311]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [323]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [313]:
data.isnull() ## data.isna()

0    False
1     True
2    False
3     True
dtype: bool

In [316]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [320]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [321]:
data.dropna()

0        1
2    hello
dtype: object

In [322]:
data.fillna(8888)

0        1
1     8888
2    hello
3     8888
dtype: object

In [324]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df.dropna() ## same as df.dropna(axis='rows'), only row without any NaN remains

0    1  2
1  2.0  3.0  5

In [325]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [333]:
df['3'] = np.nan ## adding another column
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [334]:
df.dropna(axis='columns', how='all') ### only drop if all elements is na (column)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [337]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [339]:
df.dropna(axis='rows', thresh=3) ## have at least 3 values

##similar to roll call data dropping, threshold would be missing more than 40% votes

0    1  2   3
1  2.0  3.0  5 NaN

In [340]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [342]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [341]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [344]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [343]:
data.fillna(np.mean(data))

a    1.0
b    2.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [345]:
df


0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [346]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [347]:
df.fillna(method='bfill', axis=1)

0    1    2   3
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  6.0 NaN

In [3]:
## index is constructed as tuples
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [349]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [353]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [7]:
pop[[i for i in pop.index if i[0] == 'Texas']] ## indexing needs []

(Texas, 2000)    20851820
(Texas, 2010)    25145561
dtype: int64

In [44]:
for i in pop.index:
    print(i)

('California', 2000)
('California', 2010)
('New York', 2000)
('New York', 2010)
('Texas', 2000)
('Texas', 2010)


## Better method than above

In [360]:
index = pd.MultiIndex.from_tuples(index)
index
## first set of label for State, second for year

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [361]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

#### Important

In [396]:
## this indexing is according to index levels above [state,year]
## after above reindexing, works just like `np.array`
pop[:, 2010] 

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [366]:
pop['Texas', 2010]

25145561

In [395]:
pop.loc['California':'New York']

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [394]:
pop[pop > 22000000]

California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

### convert multi indexed `series` to `DataFrame`

In [369]:
pop_df = pop.unstack() 
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [370]:
pop_df.stack() ## will convert it back to multi indexed series

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [371]:
## succinct way to represent data.
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [374]:
f_u18 = pop_df['under18'] / pop_df['total'] ## gives multi indexed series
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [376]:
 f_u18.unstack() ## convert it to df

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [378]:
# hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])
# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  36.8  53.0  37.8  32.0  37.5
     2      32.0  36.5  39.0  35.1  20.0  36.4
2014 1      27.0  37.3  28.0  35.6  52.0  36.8
     2      38.0  35.6  32.0  37.1  25.0  37.4

In [446]:
index_temp = pd.MultiIndex.from_tuples([(2013,1),(2013,2),(2014,1),
                                        (2014,2)],names=['year', 'visit'])
### more redundant way (previous method)
health_data2 = pd.DataFrame(data, index=index_temp, columns=columns)
health_data2

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  36.8  53.0  37.8  32.0  37.5
     2      32.0  36.5  39.0  35.1  20.0  36.4
2014 1      27.0  37.3  28.0  35.6  52.0  36.8
     2      38.0  35.6  32.0  37.1  25.0  37.4

In [392]:
health_data.loc[2013] ## health_data.loc[2013.:]

subject   Bob       Guido         Sue      
type       HR  Temp    HR  Temp    HR  Temp
visit                                      
1        35.0  36.8  53.0  37.8  32.0  37.5
2        32.0  36.5  39.0  35.1  20.0  36.4

In [387]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      53.0  37.8
     2      39.0  35.1
2014 1      28.0  35.6
     2      32.0  37.1

In [382]:
health_data.stack()

subject           Bob  Guido   Sue
year visit type                   
2013 1     HR    35.0   53.0  32.0
           Temp  36.8   37.8  37.5
     2     HR    32.0   39.0  20.0
           Temp  36.5   35.1  36.4
2014 1     HR    27.0   28.0  52.0
           Temp  37.3   35.6  36.8
     2     HR    38.0   32.0  25.0
           Temp  35.6   37.1  37.4

In [383]:
health_data.stack().stack()

year  visit  type  subject
2013  1      HR    Bob        35.0
                   Guido      53.0
                   Sue        32.0
             Temp  Bob        36.8
                   Guido      37.8
                   Sue        37.5
      2      HR    Bob        32.0
                   Guido      39.0
                   Sue        20.0
             Temp  Bob        36.5
                   Guido      35.1
                   Sue        36.4
2014  1      HR    Bob        27.0
                   Guido      28.0
                   Sue        52.0
             Temp  Bob        37.3
                   Guido      35.6
                   Sue        36.8
      2      HR    Bob        38.0
                   Guido      32.0
                   Sue        25.0
             Temp  Bob        35.6
                   Guido      37.1
                   Sue        37.4
dtype: float64

In [397]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  36.8  53.0  37.8  32.0  37.5
     2      32.0  36.5  39.0  35.1  20.0  36.4
2014 1      27.0  37.3  28.0  35.6  52.0  36.8
     2      38.0  35.6  32.0  37.1  25.0  37.4

In [435]:
health_data['Guido', 'HR'] ### default column index

year  visit
2013  1        53.0
      2        39.0
2014  1        28.0
      2        32.0
Name: (Guido, HR), dtype: float64

In [407]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      35.0  36.8
     2      32.0  36.5

In [415]:
health_data.loc[2013,'Bob']

type     HR  Temp
visit            
1      35.0  36.8
2      32.0  36.5

#### Important

In [421]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        35.0
      2        32.0
2014  1        27.0
      2        38.0
Name: (Bob, HR), dtype: float64

In [420]:
health_data.loc[2013,['Bob','Guido']]

subject   Bob       Guido      
type       HR  Temp    HR  Temp
visit                          
1        35.0  36.8  53.0  37.8
2        32.0  36.5  39.0  35.1

#### important

In [440]:
idx = pd.IndexSlice

In [441]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  36.8  53.0  37.8  32.0  37.5
     2      32.0  36.5  39.0  35.1  20.0  36.4
2014 1      27.0  37.3  28.0  35.6  52.0  36.8
     2      38.0  35.6  32.0  37.1  25.0  37.4

In [443]:
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      35.0  53.0  32.0
2014 1      27.0  28.0  52.0

In [444]:
health_data.loc[idx[2013, 1], idx['Bob', 'HR']] ### idx gives 

35.0

### Many of the `MultiIndex` slicing operations will fail if the index is not sorted.


In [447]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]],names = ['char', 'int'])
data = pd.Series(np.random.rand(6), index=index)
data

char  int
a     1      0.074551
      2      0.986887
c     1      0.772245
      2      0.198716
b     1      0.005522
      2      0.815461
dtype: float64

In [457]:
data['a':'b'] ## without the c component, needs to sort the index first

char  int
a     1      0.074551
      2      0.986887
b     1      0.005522
      2      0.815461
dtype: float64

In [454]:
data = data.sort_index()
data ###

char  int
a     1      0.074551
      2      0.986887
b     1      0.005522
      2      0.815461
c     1      0.772245
      2      0.198716
dtype: float64

In [469]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [467]:
pop.unstack(level=0)

California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [468]:
pop.unstack(level=1)  ### level = -1 gives the same thing as it's the last level

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [478]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [519]:
pop_flat = pop.reset_index(name='Population')
pop_flat

level_0  level_1  Population
0  California     2000    33871648
1  California     2010    37253956
2    New York     2000    18976457
3    New York     2010    19378102
4       Texas     2000    20851820
5       Texas     2010    25145561

In [520]:
pop_flat.rename(columns={"level_0": "State", "level_1": "Year"})

State  Year  Population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [523]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      35.0  36.8  53.0  37.8  32.0  37.5
     2      32.0  36.5  39.0  35.1  20.0  36.4
2014 1      27.0  37.3  28.0  35.6  52.0  36.8
     2      38.0  35.6  32.0  37.1  25.0  37.4

In [526]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     33.5  36.65  46.0  36.45  26.0  36.95
2014     32.5  36.45  30.0  36.35  38.5  37.10

In [532]:
health_data.mean(level='year',axis=0)

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     33.5  36.65  46.0  36.45  26.0  36.95
2014     32.5  36.45  30.0  36.35  38.5  37.10

In [527]:
data_mean2 = health_data.mean(level='visit')
data_mean2

subject   Bob        Guido         Sue       
type       HR   Temp    HR  Temp    HR   Temp
visit                                        
1        31.0  37.05  40.5  36.7  42.0  37.15
2        35.0  36.05  35.5  36.1  22.5  36.90

In [529]:
data_mean.mean(axis=1, level='type')

type         HR       Temp
year                      
2013  35.166667  36.683333
2014  33.666667  36.633333

#### important

In [74]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [138]:
a1 = 'ABC'
b1 = np.arange(3)

In [139]:
[str(a)+str(b) for a,b in zip(a1,b1)]

['A0', 'B1', 'C2']

In [146]:
count = 0
out = np.empty(9,dtype='<U2')
for a in a1:
    for b in b1:
        out[count] = str(a)+str(b)
        count += 1
out.reshape((3,3),order='F')      

array([['A0', 'B0', 'C0'],
       ['A1', 'B1', 'C1'],
       ['A2', 'B2', 'C2']], dtype='<U2')

In [147]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)
    

In [148]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
x = [[1, 2],
     [3, 4]]

In [160]:
#np.concatenate((x, x), axis=1) works too
np.concatenate([x, x], axis=1) ## same as np.hstack((x,x))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [151]:
#np.concatenate((x,x), axis=0) works too
np.concatenate([x, x], axis=0) ## same as np.vstack((x,x))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

## `pd.concat()`is similar to `np.concatenate`

In [158]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1, ser2]) ## pd.concat((ser1, ser2)) works too

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [170]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
display('df1', 'df2', 'pd.concat([df1, df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1, df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [173]:
pd.concat([df1, df2],axis=1).fillna(0)

A   B   A   B
1  A1  B1   0   0
2  A2  B2   0   0
3   0   0  A3  B3
4   0   0  A4  B4

In [176]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
display('df3', 'df4')

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

In [178]:
pd.concat((df3,df4),axis=1) ## same pd.concat([df3, df4], axis='col')

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [180]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
display('x', 'y')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
2  A2  B2
3  A3  B3

In [184]:
y.index = x.index

In [186]:
pd.concat([x, y]) ## works but 

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [187]:
pd.concat([x, y], verify_integrity=True) ## to allow error msg

ValueError: Indexes have overlapping values: [0, 1]

In [188]:
## new index will be created despite overlap
pd.concat([x, y], ignore_index=True) 

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [189]:
pd.concat([x, y], keys=['x', 'y']) ## like those panel earlier

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [190]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
display('df5', 'df6', 'pd.concat([df5, df6])') ## default outer join (Or)

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [191]:
display('df5', 'df6',
        "pd.concat([df5, df6], join='inner')")  ## Inner join (and)

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join='inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [192]:
display('df5', 'df6',
        "pd.concat([df5, df6], join_axes=[df5.columns])")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join_axes=[df5.columns])
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [193]:
display('df5', 'df6',
        "pd.concat([df5, df6], join_axes=[df5.columns])")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join_axes=[df5.columns])
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [194]:
display('df5', 'df6',
        "pd.concat([df5, df6], join_axes=[df6.columns])")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join_axes=[df6.columns])
    B   C    D
1  B1  C1  NaN
2  B2  C2  NaN
3  B3  C3   D3
4  B4  C4   D4

`df.append` is not very efficient. use `df.concat` instead

### Merge and join
#### above can be used too

In [195]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
display('df1', 'df2')

df1
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [197]:
df3 = pd.merge(df1, df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014